name: Unit Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: 🐘 Test on PHP ${{ matrix.php_versions }}

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.php_versions == '8.2' }}

    strategy:
      matrix:
        php_versions:
          - "7.4"
#          - "8.0"
#          - "8.1"
        dependencies:
          - "lowest"
          - "highest"
        include:
          - php_version: "8.2"
          - composer-options: "--ignore-platform-reqs"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_versions }}
        coverage: xdebug2
        # extensions: gd, zip
        tools: composer:v2

    - uses: ramsey/composer-install@v2
      with:
        ignore-cache: "yes"
        dependency-versions: "${{ matrix.dependencies }}"
        composer-options: "${{ matrix.composer-options }}"

    - name: Run test suite
      run: vendor/bin/codecept run unit --coverage-text

    - name: Run infection suite
      run: vendor/bin/infection --threads=4
